name: Compile Firmware with Arduino CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          ./bin/arduino-cli config init --config-file Embedded/arduino-cli.yaml --overwrite
          ./bin/arduino-cli config add board_manager.additional_urls \
            https://arduino.esp8266.com/stable/package_esp8266com_index.json \
            --config-file Embedded/arduino-cli.yaml
          cp Embedded/arduino-cli.yaml /home/runner/.arduino15/arduino-cli.yaml
          ./bin/arduino-cli core update-index
          cd Embedded
          mkdir -p MyAussenlicht/build
          mv MyAussenlicht.ino MyAussenlicht/MyAussenlicht.ino
          ../bin/arduino-cli core install esp8266:esp8266
          ../bin/arduino-cli compile \
            --fqbn esp8266:esp8266:d1_mini \
            --build-path MyAussenlicht/build \
            MyAussenlicht
          ls -R MyAussenlicht/build

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyAussenlicht-Firmware
          path: |
            Embedded/MyAussenlicht/build/**/*.bin
